### ISSUE TITLE
nameservice_name

### ISSUE THREAD

**Issue by VFSAS** [EmbeddedRPC/erpc-imx-demos#1]
The function _erpc_transport_rpmsg_lite_rtos_remote_init_ uses nameservice_name as a parameter. What value should be used?

**Comment by MarekNovakNXP** [comment]
Hi VFSAS,

Please use there a constant string: "rpmsg-openamp-demo-channel"
This value must match with the value in the kernel module, line 1147: https://github.com/codeauroraforum/rpmsg-sysfs/blob/0aa1817545a765c200b1b2f9b6680a420dcf9171/rpmsg_sysfs_interface.patch

Regards,
Marek
