### ISSUE TITLE
adding MPU patch to my kernel - I cannot see the new module

### ISSUE THREAD

**Issue by mhanuel26** [EmbeddedRPC/erpc-imx-demos#2]
Hi,

I am trying to port this to my imx7 using technexion pico-imx7 module.

I have added rpmsg_sysfs_interface.patch and linux-fslc-imx_4.1-1.0.x.bb to my kernel, my project is working with krogoth, the after building I cannot find the rpmsg_multiept under drivers. 

I am not sure how to confirm the patched has been added to linux kernel. 

After those changes I have bitbake core-image-base and not driver on it.

Then I rebuild doing a sstate cleanup with same result.

```
bitbake -c cleansstate linux-tn-imx
bitbake -f -c compile linux-tn-imx
bitbake -c deploy linux-tn-imx
bitbake core-image-base
```

Would you kindly give an advice please.

**Comment by Hadatko** [comment]
Hi @mhanuel26 , 
are kernel-mudules part of  you core-image base?  (kernel-modules allowed in some bb layer) You can easily checkit. Google something like adding kernel-module to core-image-minimal or core-image-base (steps are common).

If kernel-modules are part of your build then you can try enable rpmsg-multiendpoint in menuconfig.

**Comment by mhanuel26** [comment]
Hi @Hadatko 

Thanks for your response, 

I have added the line 

`IMAGE_INSTALL_append += "kernel-modules kernel-devicetree python-dev python-numpy python-argparse python-subprocess python-modules python-distribute gcc gcc-dev"
`

 to my local.conf file, which I think enable kernel-modules.

I have also buil the kernel menuconfig and looking at the RPMSG option I can only see the two defaults of original linux-tn-kernel

![imx7_kernel](https://user-images.githubusercontent.com/2257779/37680972-6456a676-2c53-11e8-9ea2-32c0a2170189.png)

But I cannot see the rpmsg_multiept module.

The files structure is below.

![source_tree](https://user-images.githubusercontent.com/2257779/37681175-e7fcb4f2-2c53-11e8-9493-45b11a444cbc.png)

There should be something else I am missing. 

Please let me know if you have any idea.

**Comment by Hadatko** [comment]
Hi @mhanuel26,
because you don't see driver in menuconfig it looks like patch in bb layer is not applied. After bitbake you should see in same directory as original rpmsg multiendpoint c source file (rpmsg_multient.c or something like that). Also kConfig file and Makefile in same directory should be changed.

Here are my working sets.
in file **sources/meta-fsl-bsp-release/imx/meta-bsp/recipes-kernel/linux/linux-imx_4.9.%.bbappend** i added **SRC_URI_append += " file://0001-rpmsg_sysfs_interface_4_9_51.patch**
Patch is located in **sources/meta-fsl-bsp-release/imx/meta-bsp/recipes-kernel/linux/linux-imx/**
_My patch is newer because i am using newer kernel - 4.9.51 and it is not working with older kernel for which was intented your patch._ 

Be sure that bitbake ends without errors.

When i was adding kernel modules for core-image-minimal i was editing **sources/poky/meta/recipes-core/images/core-image-minimal.bb**
I append kernel-modules here:
**IMAGE_INSTALL = "packagegroup-core-boot ${ROOTFS_PKGMANAGE_BOOTSTRAP} ${CORE_IMAGE_EXTRA_INSTALL} _kernel-modules_"**

**Comment by mhanuel26** [comment]
Hi @Hadatko 

I appreciate your support,

Do you mean I should not add the linux-fscl-imx_4.1-1.0.x.bb file as instructed [here](https://github.com/EmbeddedRPC/erpc-imx-demos/blob/master/MPU/setup_yocto/setup_yocto_imx7d.sh)

If so, I understand I should only add the old patch rpmsg_sysfs_interface.patch to the
 `sources/meta-fsl-bsp-release/imx/meta-bsp/recipes-kernel/linux/linux-imx/`
instead of the meta-fsl-arm also instructed in aforementioned script.

I will try that way.

Best,

**Comment by mhanuel26** [comment]
@Hadatko 
It did't work. Perhaps I should not use the meta-fsl-bsp-release folder, I guess you have it since somewhere I read that **meta-fsl-arm** is deprecated but my setup might still depend on that. 

Here is how changes looks like

![suggest_patch_1](https://user-images.githubusercontent.com/2257779/37688161-a08359e6-2c6c-11e8-8706-a2256225960e.png)

Also in my working set there was no linux-imx folder. 

The missing meta-fsl-arm might be the reason you add SRC_URI_append to .bbappend file, original script [here](https://github.com/EmbeddedRPC/erpc-imx-demos/blob/master/MPU/setup_yocto/setup_yocto_imx7d.sh) does it using file **linux-fslc-imx_4.1-1.0.x.bb**.

I understand the file linux-fslc-imx_4.1-1.0.x.bb is applied by the local.conf in meta-fsl-arm which is

```
# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have a packages directory, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "fsl-arm"
BBFILE_PATTERN_fsl-arm := "^${LAYERDIR}/"
BBFILE_PRIORITY_fsl-arm = "5"

FSL_EULA_FILE = "${LAYERDIR}/EULA"

FSL_MIRROR ?= "http://www.freescale.com/lgfiles/NMG/MAD/YOCTO/"

MIRRORS += " \
${FSL_MIRROR}	http://download.ossystems.com.br/bsp/freescale/source/ \n \
"

# Let us add layer-specific bbappends which are only applied when that
# layer is included in our configuration
BBFILES += "${@' '.join('${LAYERDIR}/%s/recipes*/*/*.bbappend' % layer \
               for layer in BBFILE_COLLECTIONS.split())}"
# Add layer-specific bb files too
BBFILES += "${@' '.join('${LAYERDIR}/%s/recipes*/*/*.bb' % layer \
               for layer in BBFILE_COLLECTIONS.split())}"
```

but it seems not , probably I am wrong.

**Comment by mhanuel26** [comment]
Hi @Hadatko,

Finally I got it, I found the layer that was needing the  SRC_URI_append for technexion imx7 is meta-edm-bsp-release, so I copy patch and add the line 

`SRC_URI += "file://rpmsg_sysfs_interface.patch"`

to **linux-tn-imx_4.1.15-2.0.0.bb** 

![edm-bsp](https://user-images.githubusercontent.com/2257779/37690007-62c1ecb2-2c76-11e8-9ee1-f059cf715a46.png)

Now I can see the files in sources as

![rpmsg_sources](https://user-images.githubusercontent.com/2257779/37690023-84e765a6-2c76-11e8-85fd-2b494a523bd6.png)

Will make use of it and report back.

**Comment by Hadatko** [comment]
Hi @mhanuel26,
i am happy for you. I was near to midnight and out of work so i couldn't send information for older kernel. This was what i was working on recently.

I am looking forward for report ;)

**Comment by mhanuel26** [comment]
Hi @Hadatko ,

I have some problem to make it work the rpmsg example, would you please see below description and let me know what might be wrong,

I have started the Cortex M4 core using the compiled **rpmsg_mcu_mpu_hello_world.bin** by changing the m4image u-boot parameter

```
reading zImage
6001232 bytes read in 390 ms (14.7 MiB/s)
Booting from mmc ...
reading rpmsg_mcu_mpu_hello_world.bin
17168 bytes read in 26 ms (644.5 KiB/s)
## Starting auxiliary core at 0x007F8000 ...
baseboard is hobbit
reading imx7d-pico_hobbit-m4.dtb
44400 bytes read in 29 ms (1.5 MiB/s)
```

The M4 debug uart don't show anything.
I know my M4 is working since I have loaded a hello world demo that prints on it, but rpmsg_mcu_mpu_hello_world do not print anything, looking at main.c code I guess it should print at least _Hardware initialized_ because the code tarts with

```
void test(void *unused)
{
    int recved = 0;
    unsigned long src;
    char buf[256];
    int len;

    hardware_init();
    PRINTF("Hardware initialized\r\n");
```

I have loaded both debug and release binaries with same result.

I have installed the python application and when called from linux it produces

```
pico-imx7:~/Devel/erpc-imx-demos/MPU/example_rpmsg$ python example.py 
Datagram endpoint Test:
Could not create endpoint!
Exception AttributeError: "RpmsgEndpoint instance has no attribute 'fd'" in <bound method RpmsgEndpoint.__del__ of <rpmsg.sysfs.RpmsgEndpoint instance at 0x76acbf08>> ignored
```

I have converted back the imx7d-pico_hobbit-m4.dtb and search for rpmsg to found

```
            rpmsg {
                compatible = "fsl,imx7d-rpmsg";
                status = "okay";
                reg = <0x9fff0000 0x73656d61>;
            };
```
The second  number is somehow different from what is defined [here](https://github.com/TechNexion/linux/commit/92ce9f20a17f104931b074e3d362225cccde97ae#diff-81438acd327810fc20dc7d280b4685c8) but I am not expert, it might be mix up with something else to get final range.

I have notice the traceback of python has a number similar to the above but different value, that is , 
_0x76acbf08_, does this have to match? what this number means?

The memory field in dts is

```
    memory {
        device_type = "memory";
        reg = <0x80000000 0x000000dc>;
        linux,usable-memory = <0x80000000 0x63707573>;
    };
```

Not sure if I have to modify somehow the M4 application, I have notice that under porting there is no platform_info.c but instead only platform.c and VRING values are not defined as I was used to see, that is

```
#define VRING0_BASE                       0xBFFF0000
#define VRING1_BASE                       0xBFFF8000
```

Will appreciate your comments,

**Comment by Hadatko** [comment]
I hope your test function in m4 app is called at the beginning of main function. I would put hardware initialization and printf as first two function in the main function.
About memory map. This area is pretty new for me. I started with it yesterday and i was able do some settings. To be sure about memory mapping you need find reference manual where is described memory mapping. There you can find physical address for shared memory (for linux A core side).  Here( reg = <0x9fff0000 0x73656d61>;)  first number means address of shared memory and second size. It is mapped in device tree because we need reserve this memory for rpmsg and forbid linux to use it for differed purpose. This (reg = <0x80000000 0x000000dc>;) is confusing for me. Like Linux can use only 0xdc size of memory. But then there is  (linux,usable-memory = <0x80000000 0x63707573>;) which looks reasonable.

Here my basic knowledge ends. I will pass this question to @MarekNovakNXP . He is autor of RPMSG-lite and also he played with Linux more than me. I hope he can bring more light here.

**Comment by mhanuel26** [comment]
Hello @Hadatko @MarekNovakNXP ,

I have sucessfully ported the M4 rpmsg example application to my pico hobbit imx7 board. Now when M4 boot it shows 
```
Hardware initialized                                                                                     
Waiting for master to get ready...                                                                       
.....................................
```
I have done several things to source code but leaving original code and adding extra folder for pico board.

Try to build erpc too but it has some problem with memory as below

```
/home/mhanuel/Devel/technexion/gcc-arm-none-eabi-4_9-2015q3/bin/../lib/gcc/arm-none-eabi/4.9.3/../../../../arm-none-eabi/bin/ld: debug/erpc_mcu_mpu_hello_world.elf section `.text' will not fit in region `m_text'
/home/mhanuel/Devel/technexion/gcc-arm-none-eabi-4_9-2015q3/bin/../lib/gcc/arm-none-eabi/4.9.3/../../../../arm-none-eabi/bin/ld: region m_text overflowed with text and data
/home/mhanuel/Devel/technexion/gcc-arm-none-eabi-4_9-2015q3/bin/../lib/gcc/arm-none-eabi/4.9.3/../../../../arm-none-eabi/bin/ld: region `m_text' overflowed by 2840 bytes
collect2: error: ld returned 1 exit status
CMakeFiles/erpc_mcu_mpu_hello_world.dir/build.make:1077: recipe for target 'debug/erpc_mcu_mpu_hello_world.elf' failed
make[2]: *** [debug/erpc_mcu_mpu_hello_world.elf] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/erpc_mcu_mpu_hello_world.dir/all' failed
make[1]: *** [CMakeFiles/erpc_mcu_mpu_hello_world.dir/all] Error 2
Makefile:76: recipe for target 'all' failed
make: *** [all] Error 2
-- TOOLCHAIN_DIR: /home/mhanuel/Devel/technexion/gcc-arm-none-eabi-4_9-2015q3/
-- BUILD_TYPE: Release
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_TOOLCHAIN_FILE
```

Anyway I want to test first  the rpmsg and now I face a problem with python in MPU.

I am not sure but in order to run example_rpmsg, should I load a kernel module? the only one that I tried to load is _imx_rpmsg_tty_. 

```
After running example.py under example_rpmsg I ot the following error
pico-imx7:~/Devel/imx/erpc-imx-demos/MPU/example_rpmsg$ python example.py 
Datagram endpoint Test2:
Traceback (most recent call last):
  File "example.py", line 111, in <module>
    sys.exit(main())
  File "example.py", line 70, in main
    RpmsgEndpoint.Types.DATAGRAM)
  File "build/bdist.linux-armv7l/egg/rpmsg/sysfs.py", line 116, in __init__
Exception
```
Am I doing something wrong or missing anything here?
Could you please let me know more details about how the python app should be setup.

I have installed module under middleware/rpmsg-python/ by doing 

python setup.py install --user

Will appreciate your comments,

**Comment by Hadatko** [comment]
Hi @mhanuel26, at least you should load multiendpoint rpmsg kernel module with modprobe (that one from patch). Otherwise it looks like you have same issue as Vadim on community https://community.nxp.com/docs/DOC-334083?commentID=52054&et=watches.email.document_comment#comment-52054 (at the bottom).

With binary size and arm gcc we are actually facing issue of size. We are not able to strip some redundant code from linker. Not sure with which version of armgcc this issue started. Try add if not present options like fno-rtti and fno-noexception. Otherwise you can look if you can't extend mtext data size in linker file (you need read memory mapping if you can extend memory).

**Comment by mhanuel26** [comment]
Hello @Hadatko ,

I have read Vadim problem which looks similar but there is no solution there or further information of exactly what was wrong, I understood he use the C code and it worked. 

First thing I did (I was doing it already) is to modprobe the kernel using
`modprobe rpmsg_multiept`
which don't output any feedback by the way. 

Let's separate things. 
### ERPC.
I could build the release version doing the flags you mentioned. 
When loading example_erpc on M4 the code seems to get stuck on  Hardware Initialized, I have included a PRINTF as below
```
void app_task(void *param)
{
    hardware_init();
    PRINTF("Hardware initialized\r\n");

    erpc_transport_t transport = erpc_transport_rpmsg_lite_rtos_remote_init(
            30, 1024, BOARD_SHARED_MEMORY_BASE,
             0, NULL);
    PRINTF("call to erpc_mbf_t\r\n");
```
and code don't reach the second PRINTF("call to erpc_mbf_t\r\n");
Further debugging shows I cannot PRINTF inside erpc_transport_rpmsg_lite_rtos_remote_init, but inside the _s_transport->init_ I have included a PRINTF also unreachable (commenting any code there). 
Do you think it might crash creating the static array 
`static ManuallyConstructed<RPMsgZCRTOSTransport> s_transport;`
I have not found any other reason since I also commented  _s_transport.construct();_ function.

Unfortunately I cannot debug using JTAG. 

### RPMSG
I have a few doubts here, the M4 runs and keeps printing dots after 
```
Hardware initialized
Waiting for master to get ready...
```
Is ok this behaviour? I have tested with only one or both of the kernel modules loaded as shown

The code that keeps waiting for something is

```
    while(!rpmsg_lite_is_link_up(my_rpmsg))
    {
       PRINTF(".");
       vTaskDelay(300);
    }
    PRINTF("Sending name service announcement to Linux...\r\n");
    rpmsg_ns_announce(my_rpmsg, ctrl_ept, "rpmsg-openamp-demo-channel", RL_NS_CREATE);
```
Does it wait for kernel module, for user space app? Could you please giveme a hint here.

```
root@pico-imx7:/home/mhanuel/Devel/imx-m4fwloader# lsmod
    Not tainted
rpmsg_multiept 15340 0 - Live 0x7f025000
imx_rpmsg_tty 2623 0 - Live 0x7f021000
```
Also, remember my dtsi rpmsg section is
```
            rpmsg {
                compatible = "fsl,imx7d-rpmsg";
                status = "okay";
                reg = <0x9fff0000 0x73656d61>;
            };
```
I have change the address defined as BOARD_SHARED_MEMORY_BASE in board.h to be
`#define BOARD_SHARED_MEMORY_BASE  ((void*)0x9FFF0000)`

Would you please let me know more details how can I debug rpmsg-lite.

Thanks in advance,

**Comment by Hadatko** [comment]
Hi @mhanuel26 , RPMSG is question more for @MarekNovakNXP. But he is busy these days.  But i think he will try answer soon. I think at first M4 app should be run, then modprobe rpmsg modul, then run Linux app (but i am not sure). If you changed address in board.h you need be sure that this address is ca access M4 and it is not mapped differently (also in linker file for M4 app is used to be shared memory address specified, but maybe that is in newer apps.). For M4 side you can try newest RPMSG-lite. There were several bug fixes. And it is still compatible to commnicate with Linux RPMSG of your version of kernel (should be, binary format of messages is same) 

If it is crashing during s_transport.construct() that means you have defined small stack size in app. This is calling class constructor on address preallocated during compaling/linking.

Linux you can debug also with **dmesg** command

**Comment by mhanuel26** [comment]
Hello @Hadatko ,

Thank your for comments,

I have increase stack size by changing the following defines in main.c

```
#define APP_TASK_STACK_SIZE 512

void* rpmsg_lite_base = BOARD_SHARED_MEMORY_BASE;

#define TASK_STACK_SIZE 1000
```

I also change linker to 

```
HEAP_SIZE  = DEFINED(__heap_size__)  ? __heap_size__  : 0x0800;
STACK_SIZE = DEFINED(__stack_size__) ? __stack_size__ : 0x0800;
```
with same results. 

The example code I am running is example_rpmsg, how can I run the newest RPMSG-Lite?

The linker ha only this address range to change but really don't know how this has to be with the 0x9FFF0000 address

```
/* Specify the memory areas */
MEMORY
{
  m_interrupts          (RX)  : ORIGIN = 0x1FFF8000, LENGTH = 0x00000240
  m_text                (RX)  : ORIGIN = 0x1FFF8240, LENGTH = 0x00007DC0
  m_data                (RW)  : ORIGIN = 0x20000000, LENGTH = 0x00008000
}
```

I really will appreciate support to move forward on this project.

Hope @MarekNovakNXP can give me some hints too.

**Comment by Hadatko** [comment]
You can replace rpmsg-lite on m4core with https://github.com/codeauroraforum/rpmsg-lite. But i am not sure how it will work with your old app. In current apps we are putting shared memory information into linker file. Maybe you can go here https://mcuxpresso.nxp.com/en/welcome download example for LPCXpresso54114. Look on rpmsg remote example.

In reference manual for board you should find shared memory mapped for Mcore perspective.

But maybe i am confusing you and we should wait for @MarekNovakNXP .

**Comment by mhanuel26** [comment]
Hi @Hadatko, @MarekNovakNXP 

Regarding the RPMSG-lite (also original RPMSG)
I finally make it work and found at least the reason why it was not working,

I was doing all my tests using the [imx-m4fwloader](https://github.com/codeauroraforum/imx-m4fwloader) tool, which I have tested using hello world without problems, that is, I can load a new hello world app that only prints to serial debug console and it works without having to configure u-boot.

For some reason with rpmsg application, using this tool makes the code to remain in this while loop forever

```
   while(!rpmsg_lite_is_link_up(my_rpmsg))
    {
       PRINTF(".");
       vTaskDelay(300);
    }
```
I was suspicious of this and decide to load using u-boot and bump, after booting without loading kernel module it goes thru, that is printing 

```
Hardware initialized                                                
Waiting for master to get ready...                                                                       
...Sending name service announcement to Linux...
Waiting for any messages from Linux...
```
When kernel module is loaded it prints
```
root@pico-imx7:~# modprobe imx_rpmsg_tty
imx_rpmsg_tty rpmsg0: new channel: 0x400 -> 0x1e!
Install rpmsg tty driver!
```
and /dev/ttyRPMSG works as expected so far!

I was thinking that u-boot was not loading the correct dtb since it might happen if .bin file is not found or readable, but I repeat the test once it was working, that is trying to load a new rpmsg application using imx-m4fwloader with same result. 
My conclusion is that there is something wrong with imx-m4fwloader that might affect rpmsg M4 applications or perhaps other type of applications causing to not  load correctly which by the way make it useless since reboot seems to be required anyway.

About the Python app, here are my findings.

Running example_rpmsg give me 

```
pico-imx7:~/Devel/erpc-imx-demos$ python MPU/example_rpmsg/example.py 
Datagram endpoint Test:
Could not create endpoint!
Exception AttributeError: "RpmsgEndpoint instance has no attribute 'fd'" in <bound method RpmsgEndpoint.__del__ of <rpmsg.sysfs.RpmsgEndpoint instance at 0x76ab6030>> ignored
```

The problem is that class RpmsgEndpoint int method is rasing an exception because of self.id = -1, that is,
```
        if self.id == -1:
            raise Exception()
```
but the real exception is because __del__ method is been called with None value in self.fd attribute, I have change the first part of __del__ method to
```
    def __del__(self):

        # Close the opened endpoint
        try:
           if self.fd is None:
              return
           os.close(self.fd)
        except:
           print "problem here with fd"
           return
```
and the example now runs and throws 

```
pico-imx7:~/Devel/erpc-imx-demos$ python MPU/example_rpmsg/example.py 
Datagram endpoint Test:
Could not create endpoint!
problem here with fd
```

It seems init method try to access /sys/class/rpmsg 
`files = os.listdir(RpmsgEndpoint.RPMSG_ROOT)`
which do not exist in my system
```
root@pico-imx7:~# ls /sys/class/
ata_device    bdi           drm           graphics      input         mem           net           ptp           rtc           sound         tty           video4linux
ata_link      block         edm           hwmon         lcd           misc          pci_bus       pwm           scsi_device   spi_master    ubi           vtconsole
ata_port      bluetooth     firmware      i2c-dev       leds          mmc_host      power_supply  regulator     scsi_disk     spidev        udc           watchdog
backlight     dma           gpio          ieee80211     mdio_bus      mtd           pps           rfkill        scsi_host     thermal       vc
```

I can see rpmsg here 
```
root@pico-imx7:~# ls /sys/bus/rpmsg/
devices            drivers            drivers_autoprobe  drivers_probe      uevent
root@pico-imx7:~# ls /sys/bus/rpmsg/devices/
rpmsg0
```
 and  the following kernel message while booting  

```
virtio_rpmsg_bus virtio0: rpmsg host is online
imx rpmsg driver is registered.
```
a little later
`virtio_rpmsg_bus virtio0: creating channel rpmsg-openamp-demo-channel addr 0x1e`

I am not sure how /sys/class/rpmsg gets populated.

Will appreciate your comments,

**Comment by mhanuel26** [comment]
@Hadatko 

Ok , I have forgotten to load the rpmsg_multiept kernel module.
Now /sys/class/rpmsg is populated.

But my application gives me the already reported error

```
pico-imx7:~/Devel/erpc-imx-demos$ python MPU/example_rpmsg/example.py 
Datagram endpoint Test:
Traceback (most recent call last):
  File "MPU/example_rpmsg/example.py", line 111, in <module>
    sys.exit(main())
  File "MPU/example_rpmsg/example.py", line 70, in main
    RpmsgEndpoint.Types.DATAGRAM)
  File "build/bdist.linux-armv7l/egg/rpmsg/sysfs.py", line 116, in __init__
Exception
```

Investigating...

**Comment by mhanuel26** [comment]
@Hadatko 

Ok, got it. 

The problem is that both kernel drivers cannot be enable since each consume a channel with M4.
After loading the rpmsg_multiept module I found you need root privileged to execute the python script.

```
pico-imx7:~/Devel/erpc-imx-demos$ sudo python MPU/example_rpmsg/example.py
Datagram endpoint Test:
TX - Status: 0, Destination: 0, Message: Hello world, Length: 11
TX - Status: 0, Destination: 0, Message: Hello world, Length: 11
TX - Status: 0, Destination: 0, Message: Hello world, Length: 11
RX - Source: 30, Message: Oh you don't say number 1024!, Length: 29
RX - Source: 30, Message: Oh you don't say number 1024!, Length: 29
RX - Source: 30, Message: Oh you don't say number 1024!, Length: 29
RX - Source: 30, Message: , Length: 0
```

I suggest to update documentation and also improve a little bit the python code to print out Exceptions by replacing this section of code 
```
    try:
        MyEndpoint = RpmsgEndpoint(
            RpmsgEndpoint.rpmsg_openamp_channel,
            RpmsgEndpoint.LOCAL_DEFAULT_ADDRESS,
            RpmsgEndpoint.Types.DATAGRAM)
    except OSError: # Nothing to be read
        print "Could not create endpoint!"
        return -1
```

with something like this
```
    try:
        MyEndpoint = RpmsgEndpoint(
            RpmsgEndpoint.rpmsg_openamp_channel,
            RpmsgEndpoint.LOCAL_DEFAULT_ADDRESS,
            RpmsgEndpoint.Types.DATAGRAM)
    except Exception as e:
        print e.message, e.args
        return -1
```

It was useful to notice the permissions since when it fails give me 
```
pico-imx7:~/Devel/erpc-imx-demos$ python MPU/example_rpmsg/example.py
Datagram endpoint Test:
 (13, 'Permission denied')
```

**Comment by Hadatko** [comment]
That's great that now it is working for you. So now we can close this thread? I am appreciating your engagement.  I will also put this link to Vadim in community.

**Comment by mhanuel26** [comment]
I think so, I appreciate your help, sometimes we only need to have another opinion to kick off things ;)

By the way, should I open an issue on imx-m4fwloader repo about the issue with rpmsg code?

**Comment by Hadatko** [comment]
I don't know anything about imx-m4loader. If you think it is issue you should report it. Thank you very much.
