### ISSUE TITLE
iMXSolox rpmsg delays

### ISSUE THREAD

**Issue by VFSAS** [EmbeddedRPC/erpc-imx-demos#3]
Could anybody explain the behaviour of rpmsg and cores?
Please, see video
https://youtu.be/ZLGuh33lR0o

In this demo I use M4 rpmsg example from "erpc-imx-demos" without sending data to A9, just receiving.
A9 side code:
#include "rpmsg_linux_endpoint.h"
int
main(int argc, const char** argv)
{

    char buf[256];
    int len;

    void* pbuf;
    pbuf = &buf;

    RPMsgEndpoint RPM(1024, 0, 30);
    RPM.init();

    while (1) {

    	len = sprintf(buf, "HELLO M4 from A9!");
    	RPM.send((uint8_t*)pbuf, 30, len);
    	usleep(1000);
    	/*RPM.receive((uint8_t*)buf, 30);
    	printf(buf);*/
    }
} /* main() */

The A9 core send messages to M4, then delay 10-15s and again sending.

**Comment by Hadatko** [comment]
Hi @VFSAS ,
could be this some issue with cache? Can be or is cache disabled?

**Comment by VFSAS** [comment]
Hi @Hadatko ,
unfortunately, I didn't play with cache.
Could you please reference me.

**Comment by chandiniib** [comment]
Hi Dusan

Could you please help us to improve performance ? i am measuring timing using MONOTONIC timers for simple call it is taking around 500 micro seconds which i was not expected .

Is there way to speed up the things ?

Thank you
Chandini

**Comment by Hadatko** [comment]
I am sorry guys. I didn't played much with RPMSG neither under Linux. Currently i don't have much time to spend on this. Maybe you can ask (if you find contact) developer of RPMSG under Linux. I think his name is Bjorn Andersson.

**Comment by Hadatko** [comment]
I think i can close this issue based on: https://github.com/EmbeddedRPC/erpc/issues/20. If it is not true it can be reopened.
